### ISSUE TITLE
Chart interpretation 

### ISSUE THREAD

**Issue by pditommaso** [wresch/python_import_problem#1]
Just a quick question: can the "Total number or concurrent interpreters" be read as the number of (python based) jobs running in a distributed cluster and accessing the shared file system in parallel ?

**Comment by wresch** [comment]
Hi Paolo,

yes that's right.  In these tests all the python code did is import a few
packages and I ran increasing numbers of concurrent jobs all starting up
from the same python on a shared (NFS) file system. The idea was to get a
more quantitative idea for the python startup problem. The whole thing had
to happen during a downtime so it was a bit rushed and I can't easily go
back and do more of this on our production system...

W

**Comment by pditommaso** [comment]
Hi Wolfgang, 

Yes, that was my understanding as well. Just wanted to double check it. Very interesting. Thanks.
